### ISSUE TITLE
Places in Charlotte not shown when destination is Charlotte and Ashville

### ISSUE THREAD

**Issue by Niranjanpandeshwar** [NischalKash/TripSage_SENG2020_Phase2#11]
![1](https://user-images.githubusercontent.com/45427747/97092347-59b19f00-1611-11eb-9ccc-545f8b3f18bd.png)

![2](https://user-images.githubusercontent.com/45427747/97092349-60d8ad00-1611-11eb-8362-a807dc836083.png)

**Comment by mangalnathanvg** [comment]
Invalid Issue
